fix: some updates

diff --git a/.github/actions/code_build/action.yaml b/.github/actions/code_build/action.yaml
--- a/.github/actions/code_build/action.yaml
+++ b/.github/actions/code_build/action.yaml
@@ -1,5 +1,7 @@
 name: Code Build 
-description: An action to build the artifact
+description: Action to build an artifact
+
+# This action allows you to build the code and create the artifact which can be a zip or a directory depending on the input given.
 
 inputs:
   workspace_name:
@@ -14,6 +16,16 @@ inputs:
     description: The base workdir (Default is ./out)
     type: string
     required: false
+  zip_artifact:
+    description: True if artifact should be zipped (Default is false)
+    type: string
+    required: false
+    default: 'false'
+  enable_turbo:
+    description: True if turbo should be enabled (Default is true)
+    type: string
+    required: false
+    default: 'true'
 
 runs:
   using: composite
@@ -22,6 +34,7 @@ runs:
       name: Checkout
 
     - name: Prune
+      if: ${{ inputs.enable_turbo == 'true' }}
       shell: bash
       run: npx turbo@1.13.3 prune --scope ${{ inputs.workspace_name }}
 
@@ -40,16 +53,76 @@ runs:
       shell: bash
       run: yarn install --immutable
       working-directory: ${{ inputs.base_workdir || './out' }}
-    
+
     - name: Build
       shell: bash
       run: yarn build
       working-directory: ${{ inputs.base_workdir || './out' }}
 
-    - name: Upload Artifact
+    # Upload the build output as an artifact
+    # The artifact is not a ZIP file but the raw contents of the build directory
+    - name: Upload Artifact ( NO ZIP )
+      if: ${{ inputs.zip_artifact == 'false' }} 
       uses: actions/upload-artifact@694cdabd8bdb0f10b2cea11669e1bf5453eed0a6 # v4.2.0
       with:
         name: ${{ inputs.bundle_name || 'bundle' }}
         path: "${{ inputs.base_workdir || './out' }}"
+        if-no-files-found: error
+        retention-days: 7
+
+    # If the user wants to zip the artifact
+    - name: Build the artifact
+      if: ${{ inputs.zip_artifact == 'true' }} 
+      id: make-artifact
+      shell: bash
+      run: |
+          set -e
+
+          # determine the entry point file name from package.json main property
+          ENTRY_POINT=$(jq -r '.main' package.json)
+
+          if [ -z $ENTRY_POINT ]; then
+            echo "::error::invalid target"
+            exit 1
+          fi
+
+          # generate node_modules folder excluding devDependencies
+          yarn workspaces focus --production
+
+          FORMAT=$(jq -r 'if .type == "module" then "esm" else "cjs" end' package.json)
+          SHORT_SHA=$(git rev-parse --short ${{ github.sha }})
+
+          mkdir ${{ github.run_id }}
+
+          # bundle compiled code, excluding node_modules 
+          curl -fsSL https://esbuild.github.io/dl/v0.21.5 | sh
+          ./esbuild index=$ENTRY_POINT --bundle --format=$FORMAT --platform=node --target=node20 --packages=external --outdir=${{ github.run_id }} --allow-overwrite
+
+          # create a new package.json file, with the updated entry point
+          jq --arg sha "+$SHORT_SHA" '{"name": .name, "version": (.version + $sha), "main": "index.js", "type": (if has("type") then .type else "commonjs" end), "dependencies": .dependencies}' package.json > ${{ github.run_id }}/package.json
+
+          DEFAULT_FILES='"host.json"'
+          FILES=$(jq -r --arg default "$DEFAULT_FILES" 'if has("files") then .files else [$default] end | join(" ")' package.json)
+
+          # create the artifact (zip) with node_modules, index.js and package.json
+          zip -r ${{ env.BUNDLE_NAME }}.zip node_modules $FILES
+          zip -ju ${{ env.BUNDLE_NAME }}.zip ${{ github.run_id }}/index.js ${{ github.run_id }}/package.json
+
+          echo "artifact-path=$(realpath ${{ env.BUNDLE_NAME }}.zip)" >> "$GITHUB_OUTPUT"
+      working-directory: ${{ env.BASE_WORKDIR }}/apps/${{ inputs.workspace_name }}
+      env:
+        YARN_NODE_LINKER: node-modules
+        YARN_NM_HOISTING_LIMITS: workspaces
+        BUNDLE_NAME: ${{ inputs.bundle_name || 'bundle' }}
+        BASE_WORKDIR: ${{ inputs.base_workdir || './out' }}
+
+    # Upload the build output as an artifact
+    # The artifact is a ZIP file
+    - name: Upload Artifact ( ZIP )
+      if: ${{ inputs.zip_artifact == 'true' }} 
+      uses: actions/upload-artifact@694cdabd8bdb0f10b2cea11669e1bf5453eed0a6 # v4.2.0
+      with:
+        name: ${{ inputs.bundle_name || 'bundle' }}
+        path: ${{ steps.make-artifact.outputs.artifact-path }}
         if-no-files-found: error
         retention-days: 7
