fix: Change bot in keep alive action and update permissions on workflow

diff --git a/.github/actions/keep-alive/action.yaml b/.github/actions/keep-alive/action.yaml
--- a/.github/actions/keep-alive/action.yaml
+++ b/.github/actions/keep-alive/action.yaml
@@ -10,7 +10,18 @@ runs:
     - name: keep-alive
       shell: bash
       run: |
-        git config --local user.email "cron@github.com"
-        git config --local user.name "Keepalive"
+        git config --local user.email "dx-pagopa-github-bot@pagopa.it"
+        git config --local user.name "dx-pagopa-bot"
         git commit --allow-empty -m "Keeping the repository alive" || echo "No changes to commit"
+        COMMIT_STATUS=$?
+        
+        if [ $COMMIT_STATUS -eq 0 ]; then
+          echo "Commit created successfully, attempting to push..."
+          git push
+        else
+          echo "Could not create commit. The repository might be inactive but cannot be kept alive through this method."
+          echo "Make sure that workflows have write permissions on the repository."
+          exit 0
+        fi
+
         git push
