feat: Added version support - test

diff --git a/.github/workflows/_validate-bash-workflows-naming.yaml b/.github/workflows/_validate-bash-workflows-naming.yaml
--- a/.github/workflows/_validate-bash-workflows-naming.yaml
+++ b/.github/workflows/_validate-bash-workflows-naming.yaml
@@ -36,21 +36,31 @@ jobs:
           NEW_FILES=$(git diff --name-only --diff-filter=A $BASE_BRANCH...$HEAD_BRANCH | grep '^.github/workflows/')
 
           # Define the naming pattern
-          # Pattern is: [_]<scope>-<type>-<description>.yaml
-          NAMING_PATTERN='^(_)?(cron|build|validate|release)-(docker|typescript|terraform|changesets|docusaurus|bash|azure|aws)-[a-z0-9-]+\.yaml$'
+          # Pattern is: [_]<scope>-<type>-<description>[-vN].yaml
+          NAMING_PATTERN='^(_)?(cron|build|validate|release)-(docker|typescript|terraform|changesets|docusaurus|bash|azure|aws)-[a-z0-9-]+(-v[0-9]+)?\.yaml$'
 
           # Check each new file
           for FILE in $NEW_FILES; do
             FILE_NAME=$(basename "$FILE")
+            if ! [[ "$FILE_NAME" =~ ^_ ]]; then
+              # If the workflow is a callable template (don't start starts with '_'), ensure '-vN' is present
+              if ! [[ "$FILE_NAME" =~ -v[0-9]+\.yaml$ ]]; then
+                echo "Error: Internal workflow file '$FILE_NAME' must include '-vN' at the end."
+                echo "Example: validate-azure-example-v1.yaml"
+                exit 1
+              fi
+            fi
+
             if ! [[ "$FILE_NAME" =~ $NAMING_PATTERN ]]; then
               echo "Error: File '$FILE_NAME' does not follow the naming convention."
-              echo "Required format: [_]<scope>-<type>-<description>.yaml"
+              echo "Required format: [_]<scope>-<type>-<description>[-vN].yaml"
               echo "  - <_> only if is an internal workflow"
               echo "  - <scope> must be one of: cron, build, validate, release"
               echo "  - <type> must be one of: docker, typescript, terraform, changesets, docusaurus, bash, azure, aws"
               echo "  - <description> must be lowercase divided by hyphens (-)"
+              echo "  - <vN> where N is a major version (required if is a callable workflow)"
               echo "  - file extension must be .yaml"
-              echo "Example: validate-bash-script-checks.yaml or _cron-azure-backup.yaml"
+              echo "Example: validate-bash-script-checks.yaml or _cron-azure-backup-v1.yaml"
               exit 1
             fi
           done
