clean up

diff --git a/.github/workflows/container_app_deploy_v1.yaml b/.github/workflows/container_app_deploy_v1.yaml
--- a/.github/workflows/container_app_deploy_v1.yaml
+++ b/.github/workflows/container_app_deploy_v1.yaml
@@ -43,15 +43,18 @@ on:
         required: true
         description: Name of the resource group of the container app
       apply_github_tags_to_image_tags:
-          type: boolean
-          required: false
-          default: false
-          description: Use GitHub tags for image tagging
-        # override_github_environment:
-      npm_script:
-        type: string
+        type: boolean
         required: false
-        description: NPM script to run to check for errors
+        default: false
+        description: Use GitHub tags for image tagging
+      environment:
+        description: Environment where the image will be deployed.
+        type: string
+        required: true
+      # npm_script:
+      #   type: string
+      #   required: false
+      #   description: NPM script to run to check for errors
 
 concurrency:
   group: ${{ github.workflow }}-cd
@@ -59,7 +62,7 @@ concurrency:
 
 env:
   IMAGE_NAME: ${{ inputs.docker_image_name }}
-  NPM_SCRIPT: ${{ inputs.npm_script }}
+  # NPM_SCRIPT: ${{ inputs.npm_script }}
 
 jobs:
   build:
@@ -96,6 +99,7 @@ jobs:
     name: Deploy To Container App
     runs-on: ubuntu-latest
     needs: build
+    environment: ${{ inputs.environment }}-cd
     permissions:
       contents: read
       id-token: write
@@ -132,18 +136,18 @@ jobs:
         run: |
           az configure --defaults group=${{ env.RESOURCE_GROUP_NAME }}
 
-      - name: Get Log Analytics Workspace ID
-        id: get_log_analytics_workspace_id
-        run: |
-          cae_id=$(az containerapp show \
-            --name ${{ env.CONTAINER_APP_NAME }} \
-            --query "properties.environmentId")
+      # - name: Get Log Analytics Workspace ID
+      #   id: get_log_analytics_workspace_id
+      #   run: |
+      #     cae_id=$(az containerapp show \
+      #       --name ${{ env.CONTAINER_APP_NAME }} \
+      #       --query "properties.environmentId")
 
-          workspace_id=$(az containerapp env show \
-            --ids $cae_id \
-            --query "properties.appLogsConfiguration.logAnalyticsConfiguration.customerId")
+      #     workspace_id=$(az containerapp env show \
+      #       --ids $cae_id \
+      #       --query "properties.appLogsConfiguration.logAnalyticsConfiguration.customerId")
 
-          echo "log_analytics_workspace_id=$workspace_id" >> $GITHUB_OUTPUT
+      #     echo "log_analytics_workspace_id=$workspace_id" >> $GITHUB_OUTPUT
 
       - name: Get Container App Current Revision
         id: get_current_revision
@@ -221,7 +225,7 @@ jobs:
         run: |
           new_revision_name=${{ steps.create_new_revision.outputs.new_revision_name }}
 
-          for percentage in 5 10 30 50 70 90 100
+          for percentage in 5 10 30 60 90 100
           do
             echo "Setting $new_revision_name traffic to $percentage%"
 
@@ -230,43 +234,43 @@ jobs:
               --revision-weight ${{ steps.get_current_revision.outputs.current_revision_name }}=$(100-$percentage) \
               --revision-weight $new_revision_name=$percentage
 
-            echo "Waiting 90 seconds before checking health and increasing traffic..."
+            echo "Waiting 90 seconds before increasing traffic..."
             sleep 90
 
-            last_check=$(date +'%Y-%m-%dT%H:%M:%S')"
+            # last_check=$(date +'%Y-%m-%dT%H:%M:%S')"
 
             # Check for error logs
-            if ([[ -z "${{ env.NPM_SCRIPT }}" ]]); then
-              error_count=$(az monitor log-analytics query \
-                --workspace ${{ steps.get_log_analytics_workspace_id.outputs.log_analytics_workspace_id}}) \
-                --analytics-query "ContainerAppLog_CL | where TimeGenerated between (datetime(2025-01-01T) .. datetime(2025-05-30)) and RevisionName_s == '$new_revision_name' | where Log_s contains 'error' or Log_s contains 'Error' or Log_s contains 'ERROR' or Log_s contains 'exception' or Log_s contains 'Exception'" \
-            else
-              echo "Running NPM script to check for errors..."
-              error_count=$(npm run ${{ env.NPM_SCRIPT }})
-            fi
+            # if ([[ -z "${{ env.NPM_SCRIPT }}" ]]); then
+            #   error_count=$(az monitor log-analytics query \
+            #     --workspace ${{ steps.get_log_analytics_workspace_id.outputs.log_analytics_workspace_id}}) \
+            #     --analytics-query "ContainerAppLog_CL | where TimeGenerated between (datetime(2025-01-01T) .. datetime(2025-05-30)) and RevisionName_s == '$new_revision_name' | where Log_s contains 'error' or Log_s contains 'Error' or Log_s contains 'ERROR' or Log_s contains 'exception' or Log_s contains 'Exception'" \
+            # else
+            #   echo "Running NPM script to check for errors..."
+            #   error_count=$(npm run ${{ env.NPM_SCRIPT }})
+            # fi
 
             # Check revision health state
-            health_state=$(az containerapp revision list \
-              --name ${{ env.CONTAINER_APP_NAME }}  \
-              --query "[?name=='$new_revision_name'].properties.healthState" -o tsv)
+            # health_state=$(az containerapp revision list \
+            #   --name ${{ env.CONTAINER_APP_NAME }}  \
+            #   --query "[?name=='$new_revision_name'].properties.healthState" -o tsv)
 
-            echo "Health check results:"
-            echo "- Error logs: $error_count"
-            echo "- Health state: $health_state"
+            # echo "Health check results:"
+            # echo "- Error logs: $error_count"
+            # echo "- Health state: $health_state"
 
             # If any errors or unhealthy state, rollback and exit
-            if [ "$error_count" -gt 0 ] || [ "$health_state" != "Healthy" ]; then
-              echo "::error::Errors detected in revision '$new_revision_name', rolling back to previous revision"
+            # if [ "$error_count" -gt 0 ] || [ "$health_state" != "Healthy" ]; then
+            #   echo "::error::Errors detected in revision '$new_revision_name', rolling back to previous revision"
 
-              az containerapp ingress traffic set \
-                --name ${{ env.CONTAINER_APP_NAME }} \
-                --revision-weight ${{ steps.get_current_revision.outputs.current_revision_name }}=100 \
-                --revision-weight $new_revision_name=0
+            #   az containerapp ingress traffic set \
+            #     --name ${{ env.CONTAINER_APP_NAME }} \
+            #     --revision-weight ${{ steps.get_current_revision.outputs.current_revision_name }}=100 \
+            #     --revision-weight $new_revision_name=0
 
-              exit 1
-            fi
+            #   exit 1
+            # fi
 
-            echo "No errors detected, continuing traffic shift"
+            # echo "No errors detected, continuing traffic shift"
           done
 
           echo "::notice::Successfully shifted 100% traffic to new revision"
