add variable to control exit code errors

diff --git a/.github/workflows/deploy-azure-webapp-v2.yaml b/.github/workflows/deploy-azure-webapp-v2.yaml
--- a/.github/workflows/deploy-azure-webapp-v2.yaml
+++ b/.github/workflows/deploy-azure-webapp-v2.yaml
@@ -27,6 +27,11 @@ on:
         type: boolean
         required: false
         default: true
+      fail_on_auto_approval_failure:
+        description: Auto-Approval job quits with non-zero code when auto approval fails. In any case, manual approval remains available
+        type: boolean
+        required: false
+        default: true
 
 concurrency:
   group: ${{ github.workflow }}-cd
@@ -46,83 +51,85 @@ jobs:
       - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
         name: Checkout
 
-      # - name: Prune
-      #   run: npx turbo@2 prune --scope ${{ env.WORKSPACE }}
+      - name: Prune
+        run: npx turbo@2 prune --scope ${{ env.WORKSPACE }}
 
-      # - name: Node Setup
-      #   uses: pagopa/dx/.github/actions/node-setup@main
-      #   with:
-      #     working_dir: ./out
+      - name: Node Setup
+        uses: pagopa/dx/.github/actions/node-setup@main
+        with:
+          working_dir: ./out
 
-      # - name: Install dependencies
-      #   run: yarn install --immutable
-      #   working-directory: ./out
+      - name: Install dependencies
+        run: yarn install --immutable
+        working-directory: ./out
 
-      # - name: Build
-      #   run: yarn build
-      #   working-directory: ./out
+      - name: Build
+        run: yarn build
+        working-directory: ./out
 
-      # - name: Build the artifact
-      #   id: make-artifact
-      #   env:
-      #     # we fall back to node-moules, even in case pnp is configured, in order to avoid bundling dependendencies
-      #     YARN_NODE_LINKER: node-modules
-      #     YARN_NM_HOISTING_LIMITS: workspaces
-      #   run: |
-      #     set -e
+      - name: Build the artifact
+        id: make-artifact
+        env:
+          # we fall back to node-moules, even in case pnp is configured, in order to avoid bundling dependendencies
+          YARN_NODE_LINKER: node-modules
+          YARN_NM_HOISTING_LIMITS: workspaces
+        run: |
+          set -e
 
-      #     # generate node_modules folder excluding devDependencies
-      #     yarn workspaces focus --production
+          # generate node_modules folder excluding devDependencies
+          yarn workspaces focus --production
 
-      #     if [ -e "next.config.js" ] && grep -q 'output: "standalone"' "next.config.js"; then
-      #       echo "::debug:: the workspace contains a Next.js standalone app"
-      #       mv .next/static .next/standalone/apps/${{ inputs.workspace_name }}/.next/
-      #       cd .next/standalone/apps/${{ inputs.workspace_name }}
-      #       zip -r $BUNDLE_NAME.zip .
-      #       echo "artifact-path=$(realpath $BUNDLE_NAME.zip)" >> "$GITHUB_OUTPUT"
-      #       exit 0
-      #     fi
+          if [ -e "next.config.js" ] && grep -q 'output: "standalone"' "next.config.js"; then
+            echo "::debug:: the workspace contains a Next.js standalone app"
+            mv .next/static .next/standalone/apps/${{ inputs.workspace_name }}/.next/
+            cd .next/standalone/apps/${{ inputs.workspace_name }}
+            zip -r $BUNDLE_NAME.zip .
+            echo "artifact-path=$(realpath $BUNDLE_NAME.zip)" >> "$GITHUB_OUTPUT"
+            exit 0
+          fi
 
-      #     # determine the entry point file name from package.json main property
-      #     ENTRY_POINT=$(jq -r '.main' package.json)
+          # determine the entry point file name from package.json main property
+          ENTRY_POINT=$(jq -r '.main' package.json)
 
-      #     if [ -z $ENTRY_POINT ]; then
-      #       echo "::error::invalid target"
-      #       exit 1
-      #     fi
+          if [ -z $ENTRY_POINT ]; then
+            echo "::error::invalid target"
+            exit 1
+          fi
 
-      #     FORMAT=$(jq -r 'if .type == "module" then "esm" else "cjs" end' package.json)
-      #     SHORT_SHA=$(git rev-parse --short ${{ github.sha }})
+          FORMAT=$(jq -r 'if .type == "module" then "esm" else "cjs" end' package.json)
+          SHORT_SHA=$(git rev-parse --short ${{ github.sha }})
 
-      #     mkdir ${{ github.run_id }}
+          mkdir ${{ github.run_id }}
 
-      #     # bundle compiled code, excluding node_modules
-      #     curl -fsSL https://esbuild.github.io/dl/v0.21.5 | sh
-      #     ./esbuild index=$ENTRY_POINT --bundle --format=$FORMAT --platform=node --target=node20 --packages=external --outdir=${{ github.run_id }} --allow-overwrite
+          # bundle compiled code, excluding node_modules
+          curl -fsSL https://esbuild.github.io/dl/v0.21.5 | sh
+          ./esbuild index=$ENTRY_POINT --bundle --format=$FORMAT --platform=node --target=node20 --packages=external --outdir=${{ github.run_id }} --allow-overwrite
 
-      #     # create a new package.json file, with the updated entry point
-      #     jq --arg sha "+$SHORT_SHA" '{"name": .name, "version": (.version + $sha), "main": "index.js", "type": (if has("type") then .type else "commonjs" end), "dependencies": .dependencies}' package.json > ${{ github.run_id }}/package.json
+          # create a new package.json file, with the updated entry point
+          jq --arg sha "+$SHORT_SHA" '{"name": .name, "version": (.version + $sha), "main": "index.js", "type": (if has("type") then .type else "commonjs" end), "dependencies": .dependencies}' package.json > ${{ github.run_id }}/package.json
 
-      #     DEFAULT_FILES="host.json"
-      #     FILES=$(jq -r --arg default "$DEFAULT_FILES" '(.files // [$default]) | join(" ")' package.json)
+          DEFAULT_FILES="host.json"
+          FILES=$(jq -r --arg default "$DEFAULT_FILES" '(.files // [$default]) | join(" ")' package.json)
 
-      #     # create the artifact (zip) with node_modules, index.js and package.json
-      #     zip -r $BUNDLE_NAME.zip node_modules $FILES
-      #     zip -ju $BUNDLE_NAME.zip ${{ github.run_id }}/index.js ${{ github.run_id }}/package.json
+          # create the artifact (zip) with node_modules, index.js and package.json
+          zip -r $BUNDLE_NAME.zip node_modules $FILES
+          zip -ju $BUNDLE_NAME.zip ${{ github.run_id }}/index.js ${{ github.run_id }}/package.json
 
-      #     echo "artifact-path=$(realpath $BUNDLE_NAME.zip)" >> "$GITHUB_OUTPUT"
-      #   working-directory: ./out/apps/${{ inputs.workspace_name }}
+          echo "artifact-path=$(realpath $BUNDLE_NAME.zip)" >> "$GITHUB_OUTPUT"
+        working-directory: ./out/apps/${{ inputs.workspace_name }}
 
-      # - name: Upload Artifact
-      #   uses: pagopa/dx/.github/actions/upload-artifact@main
-      #   with:
-      #     bundle_name: ${{ env.BUNDLE_NAME }}
-      #     file_path: ${{ steps.make-artifact.outputs.artifact-path }}
+      - name: Upload Artifact
+        uses: pagopa/dx/.github/actions/upload-artifact@main
+        with:
+          bundle_name: ${{ env.BUNDLE_NAME }}
+          file_path: ${{ steps.make-artifact.outputs.artifact-path }}
 
   approve_staging:
     name: Auto-Approve Staging Slot deployment
     runs-on: ubuntu-latest
     needs: build
+    if: ${{ inputs.use_staging_slot == false }}
+
     steps:
 
       - name: Approve Next Step
@@ -137,18 +144,26 @@ jobs:
             jq --arg GH_ENV "$REQUIRED_ENVIRONMENT" '.[] | select(.environment.name == $GH_ENV)')
 
           if [ -z "$is_environment_matching" ]; then
-            echo "::error::Environment $REQUIRED_ENVIRONMENT not found."
-            echo "::warning::Check if the deployment was already approved by one of the reviewers."
-            exit 1
+            if [ "${{ inputs.fail_on_auto_approval_failure }}" ]; then
+              echo "::error::Environment $REQUIRED_ENVIRONMENT not found."
+              echo "::warning::Check if the deployment was already approved by one of the reviewers."
+              exit 1
+            else
+              exit 0
+            fi
           fi
 
           can_user_approve=$(echo "$deployments" |
             jq '.[] | select(.current_user_can_approve == true)')
 
           if [ -z "$can_user_approve" ]; then
-            echo "::error::${{ github.actor }} is not a reviewer"
-            echo "::warning::Auto Approval not available, the user is not a reviewer of the environment $REQUIRED_ENVIRONMENT."
-            exit 1
+            if [ "${{ inputs.fail_on_auto_approval_failure }}" ]; then
+              echo "::error::${{ github.actor }} is not a reviewer"
+              echo "::warning::Auto Approval not available, the user is not a reviewer of the environment $REQUIRED_ENVIRONMENT."
+              exit 1
+            else
+              exit 0
+            fi
           fi
 
           env_id=$(echo "$deployments" | jq -r '.[0].environment.id')
@@ -167,20 +182,72 @@ jobs:
 
   deploy_staging:
     name: Deploy to Staging
-    runs-on: ubuntu-latest
-    needs: build
+    needs: [build]
+    runs-on: ${{ inputs.use_private_agent == true && 'self-hosted' || 'ubuntu-latest' }}
     environment: ${{ inputs.environment }}-cd
+    if: ${{ inputs.use_staging_slot == false }}
+    permissions:
+      id-token: write
+      contents: read
+
     steps:
-      - name: Deploy to Staging
+      - name: Download Artifact
+        uses: pagopa/dx/.github/actions/download-artifact@main
+        with:
+          bundle_name: ${{ env.BUNDLE_NAME }}
+
+      - name: Azure Login
+        uses: pagopa/dx/.github/actions/azure-login@main
+        env:
+          ARM_USE_OIDC: true
+          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
+          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
+          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
+
+      - name: Deploy to Staging Slot
         run: |
-          echo "Deploying to staging slot"
+          az webapp deploy \
+            --resource-group ${{ inputs.resource_group_name }} \
+            --name ${{ inputs.web_app_name }} \
+            --slot staging \
+            --src-path  ${{ env.BUNDLE_NAME }}.zip \
+            --type zip \
+            --async false
 
   deploy_prod:
-    name: Deploy to Prod
-    runs-on: ubuntu-latest
-    needs: deploy_staging
+    name: Swap Staging and Production Slots
+    needs: [deploy_staging]
+    runs-on: ${{ inputs.use_private_agent == true && 'self-hosted' || 'ubuntu-latest' }}
     environment: ${{ inputs.environment }}-cd
+    permissions:
+      id-token: write
+      contents: read
+
     steps:
-      - name: Deploy to Prod
+
+      - name: Azure Login
+        uses: pagopa/dx/.github/actions/azure-login@main
+        env:
+          ARM_USE_OIDC: true
+          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
+          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
+          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
+
+      - name: Swap Staging and Production Slots
+        if: ${{ inputs.use_staging_slot == true }}
         run: |
-          echo "Deploying to Prod slot"
+          az webapp deployment slot swap \
+            -g ${{ inputs.resource_group_name }} \
+            -n ${{ inputs.web_app_name }} \
+            --slot staging \
+            --target-slot production
+
+      - name: Deploy
+        if: ${{ inputs.use_staging_slot == false }}
+        run: |
+          az webapp deploy \
+            --resource-group ${{ inputs.resource_group_name }} \
+            --name ${{ inputs.web_app_name }} \
+            --src-path  ${{ env.BUNDLE_NAME }}.zip \
+            --type zip \
+            --async false
