remove permissions

diff --git a/.github/workflows/deploy-azure-webapp-v2.yaml b/.github/workflows/deploy-azure-webapp-v2.yaml
--- a/.github/workflows/deploy-azure-webapp-v2.yaml
+++ b/.github/workflows/deploy-azure-webapp-v2.yaml
@@ -46,14 +46,83 @@ jobs:
       - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
         name: Checkout
 
-  approver:
-    name: Approve Next Step
+      # - name: Prune
+      #   run: npx turbo@2 prune --scope ${{ env.WORKSPACE }}
+
+      # - name: Node Setup
+      #   uses: pagopa/dx/.github/actions/node-setup@main
+      #   with:
+      #     working_dir: ./out
+
+      # - name: Install dependencies
+      #   run: yarn install --immutable
+      #   working-directory: ./out
+
+      # - name: Build
+      #   run: yarn build
+      #   working-directory: ./out
+
+      # - name: Build the artifact
+      #   id: make-artifact
+      #   env:
+      #     # we fall back to node-moules, even in case pnp is configured, in order to avoid bundling dependendencies
+      #     YARN_NODE_LINKER: node-modules
+      #     YARN_NM_HOISTING_LIMITS: workspaces
+      #   run: |
+      #     set -e
+
+      #     # generate node_modules folder excluding devDependencies
+      #     yarn workspaces focus --production
+
+      #     if [ -e "next.config.js" ] && grep -q 'output: "standalone"' "next.config.js"; then
+      #       echo "::debug:: the workspace contains a Next.js standalone app"
+      #       mv .next/static .next/standalone/apps/${{ inputs.workspace_name }}/.next/
+      #       cd .next/standalone/apps/${{ inputs.workspace_name }}
+      #       zip -r $BUNDLE_NAME.zip .
+      #       echo "artifact-path=$(realpath $BUNDLE_NAME.zip)" >> "$GITHUB_OUTPUT"
+      #       exit 0
+      #     fi
+
+      #     # determine the entry point file name from package.json main property
+      #     ENTRY_POINT=$(jq -r '.main' package.json)
+
+      #     if [ -z $ENTRY_POINT ]; then
+      #       echo "::error::invalid target"
+      #       exit 1
+      #     fi
+
+      #     FORMAT=$(jq -r 'if .type == "module" then "esm" else "cjs" end' package.json)
+      #     SHORT_SHA=$(git rev-parse --short ${{ github.sha }})
+
+      #     mkdir ${{ github.run_id }}
+
+      #     # bundle compiled code, excluding node_modules
+      #     curl -fsSL https://esbuild.github.io/dl/v0.21.5 | sh
+      #     ./esbuild index=$ENTRY_POINT --bundle --format=$FORMAT --platform=node --target=node20 --packages=external --outdir=${{ github.run_id }} --allow-overwrite
+
+      #     # create a new package.json file, with the updated entry point
+      #     jq --arg sha "+$SHORT_SHA" '{"name": .name, "version": (.version + $sha), "main": "index.js", "type": (if has("type") then .type else "commonjs" end), "dependencies": .dependencies}' package.json > ${{ github.run_id }}/package.json
+
+      #     DEFAULT_FILES="host.json"
+      #     FILES=$(jq -r --arg default "$DEFAULT_FILES" '(.files // [$default]) | join(" ")' package.json)
+
+      #     # create the artifact (zip) with node_modules, index.js and package.json
+      #     zip -r $BUNDLE_NAME.zip node_modules $FILES
+      #     zip -ju $BUNDLE_NAME.zip ${{ github.run_id }}/index.js ${{ github.run_id }}/package.json
+
+      #     echo "artifact-path=$(realpath $BUNDLE_NAME.zip)" >> "$GITHUB_OUTPUT"
+      #   working-directory: ./out/apps/${{ inputs.workspace_name }}
+
+      # - name: Upload Artifact
+      #   uses: pagopa/dx/.github/actions/upload-artifact@main
+      #   with:
+      #     bundle_name: ${{ env.BUNDLE_NAME }}
+      #     file_path: ${{ steps.make-artifact.outputs.artifact-path }}
+
+  approve_staging:
+    name: Auto-Approve Staging Slot deployment
     runs-on: ubuntu-latest
     needs: build
-    permissions:
-      actions: read
-      contents: read
-      deployments: write
     steps:
 
       - name: Approve Next Step
