feat: insert validation for terraform version retrieved from file

diff --git a/.github/workflows/get_terraform_version.yaml b/.github/workflows/get_terraform_version.yaml
--- a/.github/workflows/get_terraform_version.yaml
+++ b/.github/workflows/get_terraform_version.yaml
@@ -17,6 +17,10 @@ jobs:
         run: |
           if [ -f ".terraform-version" ]; then
               TERRAFORM_VERSION=$(cat .terraform-version)
+              if ! [[ "$TERRAFORM_VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
+                echo "Error: Invalid Terraform version format: $TERRAFORM_VERSION"
+                exit 1
+              fi
               echo "Terraform version found in .terraform-version file: $TERRAFORM_VERSION"
           else
               TERRAFORM_VERSION="1.10.4"
