Small fixes

diff --git a/.github/workflows/infra_drift_detection.yml b/.github/workflows/infra_drift_detection.yml
--- a/.github/workflows/infra_drift_detection.yml
+++ b/.github/workflows/infra_drift_detection.yml
@@ -47,8 +47,16 @@ jobs:
       SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
       SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
     steps:
+      # Exit with error if SLACK_WEBHOOK_URL is not set
+      - name: Check Slack Webhook
+        run: |
+          if [ -z "$SLACK_WEBHOOK_URL" ]; then
+            echo "SLACK_WEBHOOK_URL is not set. Please set the secret."
+            exit 1
+          fi
+
       # Set the directory where the Terraform files are located
-      # The directory the value is then available in ${{ steps.directory.outputs.dir }}
+      # The directory value is then available in ${{ steps.directory.outputs.dir }}
       - name: Set directory
         id: directory
         env:
@@ -61,6 +69,8 @@ jobs:
             echo "Environment must be provided."
             exit 1
           else
+            # Remove trailing slash from BASE_PATH if present
+            BASE_PATH="${BASE_PATH%/}"
             # The directory is expected to be in the format
             #  infra/resources/${{ inputs.environment }}
             # Example: infra/resources/prod
@@ -81,8 +91,13 @@ jobs:
         id: set-terraform-version
         run: |
           set -eu
-          terraform_version=$(cat .terraform-version)
-          printf "terraform_version=$terraform_version" >> "$GITHUB_OUTPUT"
+          if [ -f .terraform-version ]; then
+            terraform_version=$(cat .terraform-version)
+          else
+            echo "Terraform version file not found."
+            exit 1
+          fi
+          echo "terraform_version=$terraform_version" >> "$GITHUB_OUTPUT"
 
       - uses: hashicorp/setup-terraform@a1502cd9e758c50496cc9ac5308c4843bcd56d36 # v3.0.0
         name: Setup Terraform
@@ -102,13 +117,15 @@ jobs:
         id: plan
         working-directory: ${{ steps.directory.outputs.dir }}
         run: |
-          set -euo pipefail
+          set -uo pipefail
           terraform plan -no-color -detailed-exitcode -out=plan.tfplan | grep -v "hidden-link:"
 
-          if [ ${PIPESTATUS[0]} -eq 1 ]; then
+          EXIT_CODE=${PIPESTATUS[0]}
+          if [ "$EXIT_CODE" -eq 1 ]; then
             echo "::error::Terraform plan exited with an error"
-            echo "drift_found=false" >> $GITHUB_OUTPUT
             exit 1
+          elif [ "$EXIT_CODE" -eq 2 ]; then
+            echo "::notice::Terraform plan detected changes"
           fi
 
       - name: Drift Detection
@@ -119,7 +136,6 @@ jobs:
 
           if [ ! -f plan.tfplan ]; then
             echo "::error::Terraform plan file not found."
-            echo "drift_found=false" >> "$GITHUB_OUTPUT"
             exit 1
           fi
 
@@ -129,7 +145,6 @@ jobs:
           if [ "$NO_CHANGES" -eq 0 ]; then
             echo "No drifts in this configuration"
             echo "drift_found=false" >> $GITHUB_OUTPUT
-            exit 0
           else
             echo "Drift detected:"
 
@@ -144,15 +159,14 @@ jobs:
             echo " - Resources to change: $TO_CHANGE"
             echo " - Resources to destroy: $TO_DESTROY"
           
-            # Salva le variabili nell'ambiente per l'utilizzo nei passaggi successivi
+            # Save the variables in the environment for use in the next steps
             echo "TO_ADD=$TO_ADD" >> $GITHUB_ENV
             echo "TO_CHANGE=$TO_CHANGE" >> $GITHUB_ENV
             echo "TO_DESTROY=$TO_DESTROY" >> $GITHUB_ENV
-          
-            exit 1
           fi
+        continue-on-error: true
 
-      - name: Get Workflow Data
+      - name: Get Workflow Data in order to send notifications
         id: workflow_data
         uses: actions/github-script@v7
         with:
@@ -173,11 +187,11 @@ jobs:
               commit_url: `${data.repository.html_url}/commit/${data.head_sha}`,
               committer_name: data.head_commit.committer.name
             };
-          result-encoding: string
+          result-encoding: json
 
       # Reference: https://github.com/slackapi/slack-github-action 
       - name: Drift Notification
-        if: ${{ always() && env.SLACK_WEBHOOK_URL && steps.drift.outputs.drift_found == 'true' }}
+        if: ${{ success() && steps.drift.outputs.drift_found == 'true' }}
         id: drift_notify
         uses: slackapi/slack-github-action@70cd7be8e40a46e8b0eced40b0de447bdb42f68e #v1.26.0
         with:
@@ -200,10 +214,10 @@ jobs:
                   }
                 }
               ]
-            }        
+            }
 
       - name: Failure Notification
-        if: ${{ failure() && env.SLACK_WEBHOOK_URL }}
+        if: ${{ failure() }}
         id: failure_notify
         uses: slackapi/slack-github-action@70cd7be8e40a46e8b0eced40b0de447bdb42f68e #v1.26.0
         with:
