Edited Drift function

diff --git a/.github/workflows/infra_drift_detection.yml b/.github/workflows/infra_drift_detection.yml
--- a/.github/workflows/infra_drift_detection.yml
+++ b/.github/workflows/infra_drift_detection.yml
@@ -1,6 +1,11 @@
 name: Drift Detection
 
 on:
+  # remove before PR
+  push:
+    branches:
+      - EC-281-mario
+  #
   workflow_dispatch:
     inputs:
       environment:
@@ -73,7 +78,7 @@ jobs:
           else
             # The directory is expected to be in the format
             #  infra/resources/${{ inputs.environment }}
-            # Example: infra/resources/prod
+            # Example: infra/resources/dev
             printf "dir=%q/%q" "$BASE_PATH" "$ENVIRONMENT" >> "$GITHUB_OUTPUT"
           fi
 
@@ -124,17 +129,21 @@ jobs:
         id: plan
         working-directory: ${{ steps.directory.outputs.dir }}
         run: |
-          terraform plan -lock-timeout=3000s -no-color 2>&1 | tee plan_output.txt
-
-          OUTPUT=$(grep -Ev "Refreshing state|state lock|Reading|Read" plan_output.txt | tail -c 60000)
-          printf "%s" "$OUTPUT" > plan_output_multiline.txt
-
-          if grep -q "::error::Terraform exited with code" plan_output.txt; then
-            echo "failed"
+          terraform plan -no-color -detailed-exitcode -out=plan.tfplan
+          PLAN_EXIT_CODE=$?
+          if [ $PLAN_EXIT_CODE -eq 1 ]; then
+            echo "::error::Terraform plan exited with an error"
             exit 1
-          fi
+          elif [ $PLAN_EXIT_CODE -eq 0 ]; then
+            echo "No drifts in this configuration"
+            echo "drift_found=false" >> $GITHUB_OUTPUT
+            exit 0
+          else:
+            terraform show -no-color -json plan.tfplan > plan.json
+            echo "drift_found=true" >> $GITHUB_OUTPUT
 
       - name: Drift Detection
+        if: steps.plan.outputs.drift_found == 'true'
         id: drift
         working-directory: ${{ steps.directory.outputs.dir }}
         run: |
@@ -142,23 +151,22 @@ jobs:
               echo "No drifts in this configuration"
               exit 0
           else
-              changes=$(grep 'Plan: ' plan_output.txt)
-
-              to_add=$(echo $changes | awk '{print $2}')
-              to_change=$(echo $changes | awk '{print $5}')
-              to_destroy=$(echo $changes | awk '{print $8}')
-
-              echo "Drift detected!"
-              echo "Resource to add: $to_add"
-              echo "Resource to change: $to_change"
-              echo "Resource to destroy: $to_destroy"
-
-              # Save variables to environment for use in next step
-              echo "TO_ADD=$to_add" >> $GITHUB_ENV
-              echo "TO_CHANGE=$to_change" >> $GITHUB_ENV
-              echo "TO_DESTROY=$to_destroy" >> $GITHUB_ENV
-
-              exit 1
+            # Count the number of resources to add, change and destroy
+            TO_ADD=$(jq '[.resource_changes[] | select(.change.actions | index("create"))] | length' plan.json)
+            TO_CHANGE=$(jq '[.resource_changes[] | select(.change.actions | index("update"))] | length' plan.json)
+            TO_DESTROY=$(jq '[.resource_changes[] | select(.change.actions | index("delete"))] | length' plan.json)
+          
+            echo "Drift detected!"
+            echo "- Resources to add: $TO_ADD"
+            echo "- Resources to change: $TO_CHANGE"
+            echo "- Resources to destroy: $TO_DESTROY"
+          
+            # Salva le variabili nell'ambiente per l'utilizzo nei passaggi successivi
+            echo "TO_ADD=$TO_ADD" >> $GITHUB_ENV
+            echo "TO_CHANGE=$TO_CHANGE" >> $GITHUB_ENV
+            echo "TO_DESTROY=$TO_DESTROY" >> $GITHUB_ENV
+          
+            exit 1
           fi
 
       # How to configure: https://github.com/ravsamhq/notify-slack-action
