add logic to invoke remote script

diff --git a/.github/workflows/release-azure-containerapp-v1.yaml b/.github/workflows/release-azure-containerapp-v1.yaml
--- a/.github/workflows/release-azure-containerapp-v1.yaml
+++ b/.github/workflows/release-azure-containerapp-v1.yaml
@@ -43,13 +43,13 @@ on:
         required: true
         description: Name of the resource group of the container app
       environment:
-        description: Environment where the image will be deployed.
+        description: Environment where the image will be deployed
         type: string
         required: true
-      # npm_script:
-      #   type: string
-      #   required: false
-      #   description: NPM script to run to check for errors
+      npm_script:
+        type: string
+        required: false
+        description: Path to NPM script to check for errors during canary deployment. Available only when Revision Mode is set to Multiple
 
 concurrency:
   group: ${{ github.workflow }}-cd
@@ -57,7 +57,6 @@ concurrency:
 
 env:
   IMAGE_NAME: ${{ inputs.docker_image_name }}
-  # NPM_SCRIPT: ${{ inputs.npm_script }}
 
 jobs:
   build:
@@ -124,26 +123,10 @@ jobs:
       - name: Azure Login
         uses: pagopa/dx/.github/actions/azure-login@main
 
-      - name: Allow AZ CLI Extensions
+      - name: Configure AZ CLI
         run: |
           az config set extension.use_dynamic_install=yes_without_prompt
-
-      - name: Set Default Resource Group
-        run: |
           az configure --defaults group="$RESOURCE_GROUP_NAME"
-
-      # - name: Get Log Analytics Workspace ID
-      #   id: get_log_analytics_workspace_id
-      #   run: |
-      #     cae_id=$(az containerapp show \
-      #       --name "$CONTAINER_APP_NAME" \
-      #       --query "properties.environmentId")
-
-      #     workspace_id=$(az containerapp env show \
-      #       --ids $cae_id \
-      #       --query "properties.appLogsConfiguration.logAnalyticsConfiguration.customerId")
-
-      #     echo "log_analytics_workspace_id=$workspace_id" >> $GITHUB_OUTPUT
 
       - name: Get Container App Revision Mode
         id: get_revision_mode
@@ -241,60 +224,91 @@ jobs:
 
       - name: Check for New Revision Errors and Increment Traffic
         if: ${{ steps.get_revision_mode.outputs.revision_mode == 'Multiple' && steps.create_new_revision.outputs.skip_remaining_steps == 'false' }}
+        env:
+          NPM_SCRIPT: ${{ inputs.npm_script }}
         run: |
+          set -euo
+
           new_revision_name=${{ steps.create_new_revision.outputs.new_revision_name }}
 
-          for percentage in 5 10 30 60 90 100
-          do
-            echo "Setting $new_revision_name traffic to $percentage%"
+          if [ -z "$NPM_SCRIPT" ]; then
+            echo "::notice:: No NPM script provided, skipping canary deployment"
+
+            az containerapp ingress traffic set \
+            --name "$CONTAINER_APP_NAME" \
+            --revision-weight ${{ steps.get_current_revision.outputs.current_revision_name }}=0 \
+            --revision-weight $new_revision_name=100
+
+            exit 0
+          fi
+
+          currentPercentage=0
+
+          while true; do
+
+            output="$(npm run -s "$NPM_SCRIPT" $currentPercentage)"
+            exit_code=$?
+            echo "Script Output: $output"
+
+            if [ $exit_code -ne 0 ]; then
+              echo "::error::Monitoring script failed."
+              echo "::warning::Reverting traffic to previous revision."
+
+              az containerapp ingress traffic set \
+                --name "$CONTAINER_APP_NAME" \
+                --revision-weight ${{ steps.get_current_revision.outputs.current_revision_name }}=100 \
+                --revision-weight $new_revision_name=0
+              exit 1
+            fi
+
+            # Parse JSON's output using jq.
+            swap=$(echo "$output" | jq -r '.swap // empty')
+            if [ "$swap" == "true" ]; then
+              echo "::warning::Swap to new version requested."
+              echo "::notice::Swapping all traffic to next revision."
+
+              az containerapp ingress traffic set \
+                --name "$CONTAINER_APP_NAME" \
+                --revision-weight ${{ steps.get_current_revision.outputs.current_revision_name }}=0 \
+                --revision-weight $new_revision_name=100
+              break
+            fi
+
+            nextIncrementPercentage=$(echo "$output" | jq -r '.nextIncrementPercentage')
+            afterMs=$(echo "$output" | jq -r '.afterMs')
+
+            # Validate that the fields are present
+            if [ -z "$nextIncrementPercentage" ] || [ -z "$afterMs" ]; then
+              echo "::error::Invalid output from script (missing nextIncrementPercentage or afterMs)."
+              echo "::warning::Reverting traffic to previous revision."
+
+              az containerapp ingress traffic set \
+                --name "$CONTAINER_APP_NAME" \
+                --revision-weight ${{ steps.get_current_revision.outputs.current_revision_name }}=100 \
+                --revision-weight $new_revision_name=0
+              exit 1
+            fi
+
+            echo "::notice::Next traffic percentage: $nextIncrementPercentage%"
 
             az containerapp ingress traffic set \
               --name "$CONTAINER_APP_NAME" \
-              --revision-weight ${{ steps.get_current_revision.outputs.current_revision_name }}=$(100-$percentage) \
-              --revision-weight $new_revision_name=$percentage
+              --revision-weight ${{ steps.get_current_revision.outputs.current_revision_name }}=$(100-$nextIncrementPercentage) \
+              --revision-weight $new_revision_name=$nextIncrementPercentage
 
-            echo "Waiting 90 seconds before increasing traffic..."
-            sleep 90
+            currentPercentage=$nextIncrementPercentage
 
-            # last_check=$(date +'%Y-%m-%dT%H:%M:%S')"
-
-            # Check for error logs
-            # if ([[ -z "$NPM_SCRIPT" ]]); then
-            #   error_count=$(az monitor log-analytics query \
-            #     --workspace ${{ steps.get_log_analytics_workspace_id.outputs.log_analytics_workspace_id}}) \
-            #     --analytics-query "ContainerAppLog_CL | where TimeGenerated between (datetime(2025-01-01T) .. datetime(2025-05-30)) and RevisionName_s == '$new_revision_name' | where Log_s contains 'error' or Log_s contains 'Error' or Log_s contains 'ERROR' or Log_s contains 'exception' or Log_s contains 'Exception'" \
-            # else
-            #   echo "Running NPM script to check for errors..."
-            #   error_count=$(npm run $NPM_SCRIPT)
-            # fi
-
-            # Check revision health state
-            # health_state=$(az containerapp revision list \
-            #   --name "$CONTAINER_APP_NAME" \
-            #   --query "[?name=='$new_revision_name'].properties.healthState" -o tsv)
-
-            # echo "Health check results:"
-            # echo "- Error logs: $error_count"
-            # echo "- Health state: $health_state"
-
-            # If any errors or unhealthy state, rollback and exit
-            # if [ "$error_count" -gt 0 ] || [ "$health_state" != "Healthy" ]; then
-            #   echo "::error::Errors detected in revision '$new_revision_name', rolling back to previous revision"
-
-            #   az containerapp ingress traffic set \
-            #     --name "$CONTAINER_APP_NAME" \
-            #     --revision-weight ${{ steps.get_current_revision.outputs.current_revision_name }}=100 \
-            #     --revision-weight $new_revision_name=0
-
-            #   exit 1
-            # fi
-
-            # echo "No errors detected, continuing traffic shift"
+            if [ "$nextIncrementPercentage" -ge 100 ]; then
+              echo "::notice::Successfully shifted 100% traffic to new revision"
+              break
+            else
+              delaySeconds=$((afterMs / 1000))
+              echo "Waiting for $delaySeconds seconds..."
+              sleep $delaySeconds
+            fi
           done
 
-          echo "::notice::Successfully shifted 100% traffic to new revision"
-
-      - name: Deactivate old revision
+      - name: Deactivate Old Revision
         if: ${{ steps.get_revision_mode.outputs.revision_mode == 'Multiple' && steps.create_new_revision.outputs.skip_remaining_steps == 'false' }}
         run: |
           az containerapp revision deactivate \
