Fix typo

diff --git a/.github/workflows/release-azure-appsvc-v1.yaml b/.github/workflows/release-azure-appsvc-v1.yaml
--- a/.github/workflows/release-azure-appsvc-v1.yaml
+++ b/.github/workflows/release-azure-appsvc-v1.yaml
@@ -144,6 +144,17 @@ jobs:
           ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
           ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
 
+      - name: Check if the custom warm-up is configured
+        run: |
+          IS_WARMUP_CONFIGURED=$(az webapp config appsettings list \
+            --resource-group "$RESOURCE_GROUP_NAME" \
+            --name "$WEB_APP_NAME" \
+            --query 'length([?name==`WEBSITE_SWAP_WARMUP_PING_STATUSES`||name==`WEBSITE_SWAP_WARMUP_PING_PATH`]) < `2`')
+          if [ "$IS_WARMUP_CONFIGURED" == "false" ]; then
+            echo "::error::WEBSITE_SWAP_WARMUP_PING_PATH and WEBSITE_SWAP_WARMUP_PING_STATUSES are not set. Please update the webapp module to the latest version to continue."
+            exit 1
+          fi
+
       - name: Check for existing staging slot
         id: query-staging-slot
         run: |
@@ -153,17 +164,6 @@ jobs:
             --name "$WEB_APP_NAME" \
             --query 'length([?name == `staging`]) > `0`')
           echo "use_staging_slot=$USE_STAGING_SLOT" >> "$GITHUB_OUTPUT"
-
-      - name: Check if the custom warm-up is configured
-        run: |
-          IS_WARMUP_CONFIGURED=$(az webapp config appsettings list \
-            --resource-group "$RESOURCE_GROUP_NAME" \
-            --name "$WEB_APP_NAME" \
-            --query 'length([?name==`WEBSITE_SWAP_WARMUP_PING_STATUSES`||name==`WEBSITE_SWAP_WARMUP_PING_PATH`])' < `2`)
-          if [ "$IS_WARMUP_CONFIGURED" == "false" ]; then
-            echo "::error::WEBSITE_SWAP_WARMUP_PING_PATH and WEBSITE_SWAP_WARMUP_PING_STATUSES are not set. Please update the webapp module to the latest version to continue."
-            exit 1
-          fi
 
   deploy:
     name: Deploy
