feat: create swap job for auto approval

diff --git a/.github/workflows/release-azure-containerapp-v1.yaml b/.github/workflows/release-azure-containerapp-v1.yaml
--- a/.github/workflows/release-azure-containerapp-v1.yaml
+++ b/.github/workflows/release-azure-containerapp-v1.yaml
@@ -96,14 +96,19 @@ jobs:
           push_to_registry: true
 
   release:
-    name: Deploy To Container App
+    name: Deploy Container App Revision
     runs-on: ubuntu-latest
     needs: build
     if: ${{ always() && (needs.build.result == 'success' || needs.build.result == 'skipped') }}
-    environment: ${{ inputs.environment }}-cd
+    environment: ${{ inputs.environment }}-ci
     permissions:
       contents: read
       id-token: write
+    outputs:
+      current_revision_name: ${{ steps.get_current_revision.outputs.current_revision_name }}
+      new_revision_name: ${{ steps.create_new_revision.outputs.new_revision_name }}
+      revision_mode: ${{ steps.get_revision_mode.outputs.revision_mode }}
+      skip_remaining_steps: ${{ steps.create_new_revision.outputs.skip_remaining_steps }}
     env:
       ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
       ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
@@ -169,6 +174,12 @@ jobs:
           echo "::notice::Revision mode: $revision_mode"
 
           echo "revision_mode=$revision_mode" >> $GITHUB_OUTPUT
+
+      - name: Verify Auto Approval Is Supported
+        if: ${{ inputs.disable_auto_deploy && steps.get_revision_mode.outputs.revision_mode != 'Multiple' }}
+        run: |
+          echo "::error::Auto approval before activation requires the Container App to use the Multiple revision mode."
+          exit 1
 
       - name: Get Container App Current Revision
         id: get_current_revision
@@ -252,39 +263,6 @@ jobs:
             exit 1
           fi
 
-      - name: Get Container App Id
-        id: get_container_app_id
-        if: ${{ steps.get_revision_mode.outputs.revision_mode == 'Multiple' &&
-          steps.create_new_revision.outputs.skip_remaining_steps == 'false' }}
-        run: |
-          set -euo
-
-          container_app_id=$(az containerapp show \
-            --name "$CONTAINER_APP_NAME" \
-            --query "id" \
-            --output tsv)
-
-          echo "ca_id=$container_app_id" >> $GITHUB_OUTPUT
-
-      - name: Check for New Revision Errors and Increment Traffic
-        uses: pagopa/dx/actions/incremental-rollout@main
-        if: ${{ steps.get_revision_mode.outputs.revision_mode == 'Multiple' &&
-          steps.create_new_revision.outputs.skip_remaining_steps == 'false' }}
-        with:
-          resource_group_name: ${{ env.RESOURCE_GROUP_NAME }}
-          resource_name: ${{ env.CONTAINER_APP_NAME }}
-          resource_type: "containerapp"
-
-      - name: Deactivate Old Revision
-        if: ${{ steps.get_revision_mode.outputs.revision_mode == 'Multiple' &&
-          steps.create_new_revision.outputs.skip_remaining_steps == 'false' }}
-        env:
-          CURRENT_REVISION_NAME: ${{ steps.get_current_revision.outputs.current_revision_name }}
-        run: |
-          az containerapp revision deactivate \
-            --name "$CONTAINER_APP_NAME" \
-            --revision "$CURRENT_REVISION_NAME"
-
       - name: Deactivate New Revision
         if:
           ${{ failure() && steps.get_revision_mode.outputs.revision_mode == 'Multiple'
@@ -305,10 +283,10 @@ jobs:
   auto_approve_deploy:
     name: Approve Deployment
     runs-on: ubuntu-latest
-    needs: build
+    needs: release
     # If auto approval fails, the deployment can be approved manually.
     continue-on-error: true
-    if: ${{ !inputs.disable_auto_deploy && always() && (needs.build.result == 'success' || needs.build.result == 'skipped') }}
+    if: ${{ !inputs.disable_auto_deploy && always() && needs.release.result == 'success' && needs.release.outputs.revision_mode == 'Multiple' && needs.release.outputs.skip_remaining_steps == 'false' }}
 
     steps:
       - name: Approve deployment
@@ -351,3 +329,55 @@ jobs:
             -F "environment_ids[]=$environment_id" \
             -f "state=approved" \
             -f "comment=Approved automatically by the workflow."
+
+  swap:
+    name: Activate Container App Revision
+    runs-on: ubuntu-latest
+    needs: release
+    if: ${{ always() && needs.release.result == 'success' && needs.release.outputs.revision_mode == 'Multiple' && needs.release.outputs.skip_remaining_steps == 'false' }}
+    environment: ${{ inputs.environment }}-cd
+    permissions:
+      contents: read
+      id-token: write
+    env:
+      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
+      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
+      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
+      CONTAINER_APP_NAME: ${{ inputs.container_app }}
+      CURRENT_REVISION_NAME: ${{ needs.release.outputs.current_revision_name }}
+      NEW_REVISION_NAME: ${{ needs.release.outputs.new_revision_name }}
+      RESOURCE_GROUP_NAME: ${{ inputs.resource_group_name }}
+
+    steps:
+      - name: Cloud Login
+        uses: pagopa/dx/actions/csp-login@main
+
+      - name: Configure AZ CLI
+        run: |
+          az config set extension.use_dynamic_install=yes_without_prompt
+          az configure --defaults group="$RESOURCE_GROUP_NAME"
+
+      - name: Check for New Revision Errors and Increment Traffic
+        uses: pagopa/dx/actions/incremental-rollout@main
+        with:
+          resource_group_name: ${{ env.RESOURCE_GROUP_NAME }}
+          resource_name: ${{ env.CONTAINER_APP_NAME }}
+          resource_type: "containerapp"
+
+      - name: Deactivate Old Revision
+        run: |
+          az containerapp revision deactivate \
+            --name "$CONTAINER_APP_NAME" \
+            --revision "$CURRENT_REVISION_NAME"
+
+      - name: Deactivate New Revision
+        if: ${{ failure() }}
+        run: |
+          az containerapp ingress traffic set \
+            --name "$CONTAINER_APP_NAME" \
+            --revision-weight "$CURRENT_REVISION_NAME"=100 "$NEW_REVISION_NAME"=0 \
+            --output table
+
+          az containerapp revision deactivate \
+            --name "$CONTAINER_APP_NAME" \
+            --revision "$NEW_REVISION_NAME"
