Add Auto-Approve Staging Slot Deployment

diff --git a/.github/workflows/release-azure-webapp-v1.yaml b/.github/workflows/release-azure-webapp-v1.yaml
--- a/.github/workflows/release-azure-webapp-v1.yaml
+++ b/.github/workflows/release-azure-webapp-v1.yaml
@@ -22,6 +22,11 @@ on:
         type: boolean
         required: false
         default: true
+      disable_auto_staging_deploy:
+        description: Enable automatic deployments to the staging slot, bypassing the need for manual approval. If this setting is true, ensure that `use_staging_slot` is also enabled.
+        type: boolean
+        required: false
+        default: false
       use_private_agent:
         description: Use a private agent to deploy the built artifact.
         type: boolean
@@ -93,7 +98,7 @@ jobs:
             exit 0
           fi
 
-          if [ "$PACKAGE_MANAGER" == "pnpm" ]; then
+          if [ "$PACKAGE_MANAGER" = "pnpm" ]; then
             pnpm --filter $WORKSPACE_NAME deploy --prod bundle
             cd bundle && zip -r $BUNDLE_NAME.zip .
             echo "artifact-path=$(realpath $BUNDLE_NAME.zip)" >> $GITHUB_OUTPUT
@@ -180,6 +185,55 @@ jobs:
             --src-path "$BUNDLE_NAME.zip" \
             --type zip \
             --async false
+
+  auto_approve_staging_deploy:
+    name: Auto-Approve Staging Slot Deployment
+    runs-on: ubuntu-latest
+    needs: [build]
+
+    if: ${{ !github.event.act && inputs.use_staging_slot && !inputs.disable_auto_staging_deploy }}
+
+    steps:
+      - name: Approve Next Step
+        env:
+          GH_TOKEN: ${{ secrets.GH_TOKEN_DEPLOYMENT_APPROVAL }}
+          REQUIRED_ENVIRONMENT: ${{ inputs.environment }}-cd
+        run: |
+          if [ -z "$GH_TOKEN" ]; then
+            echo "::error::GH_TOKEN_DEPLOYMENT_APPROVAL secret is not set."
+            exit 1
+          fi
+
+          DEPLOYMENTS=$(gh api \
+            -H "Accept: application/vnd.github+json" \
+            /repos/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID/pending_deployments)
+
+          ENVIRONMENT=$(jq -r '.[].environment.name' <<< "$DEPLOYMENTS")
+
+          if [ "$ENVIRONMENT" != "$REQUIRED_ENVIRONMENT" ]; then
+            echo "::error::Environment $REQUIRED_ENVIRONMENT not found."
+            echo "::warning::Check if the deployment was already approved by one of the reviewers."
+            exit 1
+          fi
+
+          CURRENT_USER_CAN_APPROVE=$(jq -r '.[].current_user_can_approve' <<< "$DEPLOYMENTS")
+
+          if [ "$CURRENT_USER_CAN_APPROVE" != true ]; then
+            GITHUB_USER=$(gh api user | jq -r '.login')
+            echo "::error::$GITHUB_USER is not a reviewer"
+            echo "::warning::Auto Approval not available, the user is not a reviewer of the environment $REQUIRED_ENVIRONMENT."
+            exit 1
+          fi
+
+          ENV_ID=$(jq -r '.[].environment.id' <<< "$DEPLOYMENTS")
+
+          gh api \
+            --method POST \
+            -H "Accept: application/vnd.github+json" \
+            /repos/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID/pending_deployments \
+            -F "environment_ids[]=$ENV_ID" \
+            -f "state=approved" \
+            -f "comment=Auto approve for staging slot"
 
   swap_staging_production:
     name: Swap Staging and Production Slots
