Add fail_on_error input to static_analysis

diff --git a/.github/workflows/static_analysis.yaml b/.github/workflows/static_analysis.yaml
--- a/.github/workflows/static_analysis.yaml
+++ b/.github/workflows/static_analysis.yaml
@@ -107,7 +107,7 @@ jobs:
           PRE_COMMIT_VERBOSE: ${{ inputs.verbose && '1' || '0' }}
           LOCK_MODULES_JSON_OUTPUT_FILE: "lock_output.json"
         run: |
-          set -eu
+          set +e  # Continue execution even if pre-commit fails
 
           echo "Start pre-commit on specific folder ${{ inputs.folder }}"
 
@@ -123,7 +123,7 @@ jobs:
           PRE_COMMIT_VERBOSE: ${{ inputs.verbose && '1' || '0' }}
           LOCK_MODULES_JSON_OUTPUT_FILE: "lock_output.json"
         run: |
-          set -eu
+          set +e  # Continue execution even if pre-commit fails
 
           echo "Start pre-commit only on modified files"
           echo "- FROM  Base ref: origin/${{ github.event.pull_request.base.ref }}"
@@ -136,6 +136,13 @@ jobs:
             --to-ref origin/${{ github.event.pull_request.head.ref }} \
             ${{ inputs.check_to_run }} 2>&1 | tee /tmp/pre-commit-output.log
 
+          PRE_COMMIT_EXIT_CODE=${PIPESTATUS[0]}
+          echo "PRE_COMMIT_EXIT_CODE=$PRE_COMMIT_EXIT_CODE" >> $GITHUB_ENV
+
+          if [[ $PRE_COMMIT_EXIT_CODE -ne 0 && "${{ inputs.fail_on_error }}" == "true" ]]; then
+            exit $PRE_COMMIT_EXIT_CODE
+          fi
+
       - name: Run pre-commit
         if: ${{ inputs.folder == '' && (!github.event_name == 'pull_request' || !inputs.enable_modified_files_detection) }}
         id: pre_commit
@@ -143,7 +150,7 @@ jobs:
           PRE_COMMIT_VERBOSE: ${{ inputs.verbose && '1' || '0' }}
           LOCK_MODULES_JSON_OUTPUT_FILE: "lock_output.json"
         run: |
-          set -eu
+          set +e  # Continue execution even if pre-commit fails
 
           echo "Start pre-commit on all files"
 
@@ -152,6 +159,13 @@ jobs:
             --show-diff-on-failure \
             --all-files \
             ${{ inputs.check_to_run }} 2>&1 | tee /tmp/pre-commit-output.log
+
+          PRE_COMMIT_EXIT_CODE=${PIPESTATUS[0]}
+          echo "PRE_COMMIT_EXIT_CODE=$PRE_COMMIT_EXIT_CODE" >> $GITHUB_ENV
+
+          if [[ $PRE_COMMIT_EXIT_CODE -ne 0 && "${{ inputs.fail_on_error }}" == "true" ]]; then
+            exit $PRE_COMMIT_EXIT_CODE
+          fi
 
       - name: Summarize pre-commit results
         if: always()
