update existing workflow

diff --git a/.github/workflows/web_app_deploy.yaml b/.github/workflows/web_app_deploy.yaml
--- a/.github/workflows/web_app_deploy.yaml
+++ b/.github/workflows/web_app_deploy.yaml
@@ -27,6 +27,16 @@ on:
         type: boolean
         required: false
         default: true
+      enable_staging_auto_deployment:
+        description: Enable to deploy to staging slot without an approval
+        type: boolean
+        required: false
+        default: false
+      force_approval_exit_code:
+        description: If "enable_staging_auto_deployment" is enabled and you do not have an approval step for deployments in the chosen environment, set this option to true to force a successful exit code for staging deployment auto-approval job. It is useful to set a green mark in the GitHub Action tab to indicate apparent completion
+        type: boolean
+        required: false
+        default: false
 
 concurrency:
   group: ${{ github.workflow }}-cd
@@ -34,6 +44,9 @@ concurrency:
 
 env:
   BUNDLE_NAME: bundle
+  RESORUCE_GROUP_NAME: ${{ inputs.resource_group_name }}
+  WEB_APP_NAME: ${{ inputs.web_app_name }}
+  FORCE_APPROVAL_EXIT_CODE: ${{ inputs.force_approval_exit_code }}
 
 jobs:
   build:
@@ -68,6 +81,7 @@ jobs:
           # we fall back to node-moules, even in case pnp is configured, in order to avoid bundling dependendencies
           YARN_NODE_LINKER: node-modules
           YARN_NM_HOISTING_LIMITS: workspaces
+        working-directory: ./out/apps/$WORKSPACE
         run: |
           set -e
 
@@ -76,9 +90,9 @@ jobs:
 
           if [ -e "next.config.js" ] && grep -q 'output: "standalone"' "next.config.js"; then
             echo "::debug:: the workspace contains a Next.js standalone app"
-            mv .next/static .next/standalone/apps/${{ inputs.workspace_name }}/.next/
-            cd .next/standalone/apps/${{ inputs.workspace_name }}
-            zip -r $BUNDLE_NAME.zip .
+            mv .next/static .next/standalone/apps/"$WORKSPACE"/.next/
+            cd .next/standalone/apps/"$WORKSPACE"
+            zip -r "$BUNDLE_NAME".zip .
             echo "artifact-path=$(realpath $BUNDLE_NAME.zip)" >> "$GITHUB_OUTPUT"
             exit 0
           fi
@@ -111,7 +125,6 @@ jobs:
           zip -ju $BUNDLE_NAME.zip ${{ github.run_id }}/index.js ${{ github.run_id }}/package.json
 
           echo "artifact-path=$(realpath $BUNDLE_NAME.zip)" >> "$GITHUB_OUTPUT"
-        working-directory: ./out/apps/${{ inputs.workspace_name }}
 
       - name: Upload Artifact
         uses: pagopa/dx/.github/actions/upload-artifact@main
@@ -119,11 +132,68 @@ jobs:
           bundle_name: ${{ env.BUNDLE_NAME }}
           file_path: ${{ steps.make-artifact.outputs.artifact-path }}
 
-  deploy:
-    name: Deploy
-    if: ${{ !github.event.act }}
+  # Automatically approve deployment to staging slot
+  approve_staging:
+    name: Auto-Approve Staging Slot Deployment
+    runs-on: ubuntu-latest
     needs: [build]
+    if: ${{ inputs.enable_staging_auto_deployment == true && inputs.use_staging_slot == true }}
+
+    steps:
+
+      - name: Approve Next Step
+        run: |
+
+          deployments=$(gh api \
+            -H "Accept: application/vnd.github+json" \
+            -H "X-GitHub-Api-Version: 2022-11-28" \
+            /repos/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID/pending_deployments)
+
+          is_environment_matching=$(echo "$deployments" |
+            jq --arg GH_ENV "$REQUIRED_ENVIRONMENT" '.[] | select(.environment.name == $GH_ENV)')
+
+          if [ -z "$is_environment_matching" ]; then
+            if [ "$FORCE_APPROVAL_EXIT_CODE" ]; then
+              exit 0
+            else
+              echo "::error::Environment $REQUIRED_ENVIRONMENT not found."
+              echo "::warning::Check if the deployment was already approved by one of the reviewers."
+              exit 1
+            fi
+          fi
+
+          can_user_approve=$(echo "$deployments" |
+            jq '.[] | select(.current_user_can_approve == true)')
+
+          if [ -z "$can_user_approve" ]; then
+            if [ "$FORCE_APPROVAL_EXIT_CODE" ]; then
+              exit 0
+            else
+              echo "::error::${{ github.actor }} is not a reviewer"
+              echo "::warning::Auto Approval not available, the user is not a reviewer of the environment $REQUIRED_ENVIRONMENT."
+              exit 1
+            fi
+          fi
+
+          env_id=$(echo "$deployments" | jq -r '.[0].environment.id')
+
+          gh api \
+            --method POST \
+            -H "Accept: application/vnd.github+json" \
+            -H "X-GitHub-Api-Version: 2022-11-28" \
+            /repos/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID/pending_deployments \
+            -F "environment_ids[]=$env_id" \
+            -f "state=approved" \
+            -f "comment=Auto approve for staging slot"
+        env:
+          GH_TOKEN: ${{ secrets.GH_TOKEN_DEPLOYMENT_APPROVAL }}
+          REQUIRED_ENVIRONMENT: ${{ inputs.environment }}-cd
+
+  deploy_staging:
+    name: Deploy to Staging
     runs-on: ${{ inputs.use_private_agent == true && 'self-hosted' || 'ubuntu-latest' }}
+    needs: [build]
+    if: ${{ inputs.use_staging_slot == true }}
     environment: ${{ inputs.environment }}-cd
     permissions:
       id-token: write
@@ -143,32 +213,50 @@ jobs:
           ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
           ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
 
-      - name: Deploy
-        if: ${{ inputs.use_staging_slot == false }}
-        run: |
-          az webapp deploy \
-           --resource-group ${{ inputs.resource_group_name }} \
-           --name ${{ inputs.web_app_name }} \
-           --src-path  ${{ env.BUNDLE_NAME }}.zip \
-           --type zip \
-           --async false
-
       - name: Deploy to Staging Slot
-        if: ${{ inputs.use_staging_slot == true }}
         run: |
           az webapp deploy \
-           --resource-group ${{ inputs.resource_group_name }} \
-           --name ${{ inputs.web_app_name }} \
-           --slot staging \
-           --src-path  ${{ env.BUNDLE_NAME }}.zip \
-           --type zip \
-           --async false
+            --resource-group "$RESORUCE_GROUP_NAME" \
+            --name "$WEB_APP_NAME" \
+            --slot staging \
+            --src-path "$BUNDLE_NAME".zip \
+            --type zip \
+            --async false
+
+  deploy_prod:
+    name: Swap Staging and Production Slots
+    runs-on: ${{ inputs.use_private_agent == true && 'self-hosted' || 'ubuntu-latest' }}
+    needs: [build, deploy_staging]
+    if: ${{ always() && !github.event.act && needs.deploy_staging.result == 'skipped' || needs.deploy_staging.result == 'success' }}
+    environment: ${{ inputs.environment }}-cd
+    permissions:
+      id-token: write
+      contents: read
+
+    steps:
+      - name: Azure Login
+        uses: pagopa/dx/.github/actions/azure-login@main
+        env:
+          ARM_USE_OIDC: true
+          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
+          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
+          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
 
       - name: Swap Staging and Production Slots
         if: ${{ inputs.use_staging_slot == true }}
         run: |
           az webapp deployment slot swap \
-            -g ${{ inputs.resource_group_name }} \
-            -n ${{ inputs.web_app_name }} \
+            --resource-group "$RESORUCE_GROUP_NAME" \
+            --name "$WEB_APP_NAME" \
             --slot staging \
             --target-slot production
+
+      - name: Deploy
+        if: ${{ inputs.use_staging_slot == false }}
+        run: |
+          az webapp deploy \
+            --resource-group "$RESORUCE_GROUP_NAME" \
+            --name "$WEB_APP_NAME" \
+            --src-path "$BUNDLE_NAME.zip" \
+            --type zip \
+            --async false
